### PR TITLE
Fix 'composer-runtime-api' sorting

### LINKED ISSUE #18: Take Composer runtime API in account when sorting requirements
see https://github.com/contao/contao/pull/3935#discussion_r785428420

We should probably adjust these:
https://github.com/contao/monorepo-tools/blob/14d48eaf504d697131e7ba60e5ce458f62fc296d/src/Command/ComposerJsonCommand.php#L394-L421

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #18.

### CODE REVIEW

File: src/Command/ComposerJsonCommand.php [hunk 1]
```diff
@@ -416,6 +416,14 @@ static function ($a, $b) {
                     return 1;
                 }
 
+                if ('composer-runtime-api' === $a) {
+                    return -1;
+                }
+
+                if ('composer-runtime-api' === $b) {
+                    return 1;
+                }
```
Comment (ausi) [inline src/Command/ComposerJsonCommand.php]:
```suggestion
                if (strpos($a, '/') === false && strpos($b, '/') !== false) {
                    return -1;
                }

                if (strpos($b, '/') === false && strpos($a, '/') !== false) {
                    return 1;
                }
```

How about sorting all dependencies that don’t have a slash in them after the PHP extensions?

Comment (m-vo) [reply src/Command/ComposerJsonCommand.php]: Good idea 👍

**Comment by ausi** [comment]
Thank you @m-vo
